CiscoDevNet/coding-series-learning-labs

labs/coding-101-rest-basics-ga/2.md
It just says Create, Update, Delete next to the CRUD acronym. Add "Read"
@annegentle
=> Add "Read" to CRUD Definition

labs/coding-101-rest-basics-ga/3.md
Under About Authentication there is a missing word in the first sentence
@annegentle
=> Added word "access" - missing from sentence

labs/coding-101-rest-basics-ga/4.md
Changed title to Constructing a REST Call.
@annegentle
=> 4.md Change misleading title

labs/coding-101-rest-basics-ga/5.md
Added link to SOAPUI
https://www.soapui.org/
@annegentle
=> 5.md - SOAPUI

labs/coding-101-rest-basics-ga/5.md
For steps A,B,C update under Using Postman to make REST API Calls.
Also, update link to proper sandbox link.
https://user-images.githubusercontent.com/4925801/34445847-841d7456-eca4-11e7-8744-165f8ebeae7e.png
@annegentle
=> 5.md - Update postman screenshot

labs/coding-101-rest-basics-ga/6.md
Add to look for Get /host under Inventory
@annegentle
=> 6.md - Include Inventory Info

labs/coding-101-rest-basics-ga/6.md
Change the word to "returned"
@annegentle
=> 6.md - "returned" grammar

labs/coding-101-rest-basics-ga/8.md
Screenshot needs to reflect proper link for sandbox.
https://user-images.githubusercontent.com/4925801/34446442-ffffe924-eca8-11e7-8d6e-b3e8a4650f8f.png
@annegentle
=> 8.md - change screenshot for network-device

labs/coding-102-rest-python-ga/1.md
Update sandbox link
https://sandboxapicem.cisco.com/
@annegentle
=> 102 - 1.md - Update sandbox link

labs/coding-102-rest-python-ga/2.md
=> 102-2.md-Update sandbox link

labs/coding-102-rest-python-ga/4.md
=> 102-4.md-Update sandbox link

labs/coding-102-rest-python-ga/4.md
In step 2 it should be get-network-devices.py
@annegentle
=> 102-4.md-wrong file name

labs/coding-102-rest-python-ga/6.md
=> 102-6.md-update sandbox link

labs/coding-102-rest-python-ga/6.md
More information on decorators.
https://www.python.org/dev/peps/pep-0318/
@annegentle
=> 102-6.md-decorator information

labs/coding-101-rest-basics-ga/2.md
The old link led to a site associated with a phishing scam, according to Google.
@annegentle
=> Changed link to REST help

labs/coding-102-rest-python-ga/5.md
Include link to find out more about loops and conditionals.
https://learninglabs.cisco.com/tracks/devnet-beginner/fundamentals/00-prep-04-python-primer2/step/4
@annegentle
=> 102-5.md-More loop info

labs/coding-101-rest-basics-ga/6.md
Under Headers at the bottom, it assumes the reader knows what we're talking about when maybe they've never done this before. The screenshot is on the next page. I'm going to add "see screenshot on next page."
@annegentle
=> 6.md - Screenshot info

labs/coding-101-rest-basics-ga/7.md
sandboxapicem.cisco.com
@annegentle
=> 7.md - change screenshot and sandbox link

labs/coding-101-rest-basics-ga/7.md
The host info screenshot also needs to be updated to reflect the correct sandbox link.
https://user-images.githubusercontent.com/4925801/34446255-841a6006-eca7-11e7-9be6-507f378615a4.png
@annegentle
=> 7.md - change screenshot host info

labs/coding-102-rest-python-ga/4.md
Added link to learn more about Python Functions
https://learninglabs.cisco.com/tracks/devnet-beginner/fundamentals/00-prep-04-python-primer2/step/4
@annegentle
=> 102-4.md-Add link to Function info

labs/coding-101-rest-basics-ga/4.md
Update the API reference to remain consistent and tell users to pick the proper API version.
@annegentle
=> 4.md - Update API Reference

labs/coding-101-rest-basics-ga/4.md
Original link takes you to DevNet home page. Use https://sandboxapicem.cisco.com/ to stay consistent with lab setup.
@annegentle
=> 4.md - change link to sandbox

labs/coding-102-rest-python-ga/6.md
update link to sandboxapicem.cisco.com
@annegentle
=> 102-6.md-update controller link

labs/coding-102-rest-python-ga/3.md
=> 102-3.md-Update sandbox link

labs/coding-202-parsing-json/1.md, labs/coding-202-parsing-json/4.md, labs/coding-210-parsing-json-c++/1.md, labs/coding-210-parsing-json-c++/6.md
=> Change the JSON Tutorial link on w3schools.com

labs/coding-101-rest-basics-ga/coding-101-rest-basics-ga.json
* Addresses https://github.com/CiscoDevNet/learning-labs-issues/issues/44
* Redirecting Coding 101 to `what-are-rest-apis`
=> Redirecting Coding 101

labs/coding-102-rest-python-ga/coding-102-rest-python-ga.json
Adding a redirect to the Python lab
=> Setting Coding 102 to redirect to Python2 lab

labs/coding-202-parsing-json/1.md
Python3 handles self signed certs differently
=> Update to include handling of self-signed certs

labs/coding-201-parsing-xml/1.md
Start to address Issue # 106 https://github.com/CiscoDevNet/learning-labs-issues/issues/106
=> Since the Sandbox is unavailable, revise as example
